searchBar/searchBar/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('search/',include('searchBarApp.urls')),
    #path('search/', views.index),
    #path('search/result', views.result, name='result'),

    #path('create/',views.create_industry)
]#+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


#if settings.DEBUG:
#    urlpatterns +=[
#     path('media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT,}),
#    ]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

searchBar/searchBarApp/urls.py
from django.urls import path
from django.conf import settings
from django.views.static import serve
from searchBarApp import views
from django.conf.urls.static import static

app_name="searchBarApp"
urlpatterns = [
    path('searching/', views.index,name="searching"),
    path('searching/result', views.result, name="result"),
    path('Assembling',views.Assembling,name="Assembling"),
    path('Automobiles',views.Automobiles,name="Automobiles"),
    path('Manufacturing',views.Manufacturing,name="Manufacturing"),
    path('IT_Companies',views.IT_Companies,name="IT_Companies"),
    path('contact',views.contact,name="contact"),
    path('blog',views.blog,name="blog"),
    path('faq',views.faq,name="faq"),
    path('about',views.about,name="about"),
    path('services',views.services,name="services"),
    path('read',views.read,name="read"),
    path('base',views.base,name="base"),
]

searchBar/searchBarApp/models.py
from django.db import models

# Create your models here.

class industry(models.Model):
    id_name=models.CharField(max_length=264,unique=True)
    category=models.CharField(max_length=264,default='')
    image=models.ImageField(blank=True,null=True)
    location=models.CharField(max_length=528,default='')
    date=models.DateField(blank=True, null=True,default='')
    About=models.TextField(default='')

    def __str__(self):
        return self.id_name

searchBar/searchBarApp/forms.py
from django import forms

class FormName(forms.Form):
    input=forms.CharField()
    select_type=forms.ChoiceField()

searchBar/searchBarApp/views.py
from django.shortcuts import render,get_object_or_404
from .models import industry
from . import forms
# Create your views here.

def index(request):
    queryset = industry.objects.all()

    queryset2 = industry.objects.filter(category__contains="Manufacturing")

    queryset3 = industry.objects.filter(category__contains="Automobile")

    queryset4 = industry.objects.filter(category__contains="Assembling")

    queryset5 = industry.objects.filter(category__contains="IT Companies")


    context = {
        "objects" : queryset,
        "objects2" : queryset2,
        "objects3":queryset3,
        "objects4":queryset4,
        "objects5":queryset5,

    }
    return render(request,'searchBarApp/index.html',context)

def result(request,name=None):

    queryset = industry.objects.all()

    queryset2 = industry.objects.filter(category__contains="Manufacturing")

    queryset3 = industry.objects.filter(category__contains="Automobile")

    queryset4 = industry.objects.filter(category__contains="Assembling")

    queryset5 = industry.objects.filter(category__contains="IT Companies")

    query = request.POST['query']
    temp = query.upper()
    k=404
    for object in queryset:
        if object.id_name.upper() == temp:
            k = object.id

    if(k==404):
        k = None
        context = {
            "key" : False,
            "objects" : queryset,
            "objects2" : queryset2,
            "objects3":queryset3,
            "objects4":queryset4,
            "objects5":queryset5,
        }
    else:
        context = {
            "instance" : get_object_or_404(industry, id=k),
            "objects" : queryset,
            "objects2" : queryset2,
            "objects3":queryset3,
            "objects4":queryset4,
            "objects5":queryset5,
            "key" : True
        }
    return render(request,'searchBarApp/result.html',context)

def Assembling(request,name=None):

    queryset = industry.objects.all()

    queryset2 = industry.objects.filter(category__contains="Manufacturing")

    queryset3 = industry.objects.filter(category__contains="Automobile")

    queryset4 = industry.objects.filter(category__contains="Assembling")

    queryset5 = industry.objects.filter(category__contains="IT Companies")


    context = {
        "objects" : queryset,
        "objects2" : queryset2,
        "objects3":queryset3,
        "objects4":queryset4,
        "objects5":queryset5,

    }
    return render(request,'searchBarApp/Assembling.html',context)

def Automobiles(request,name=None):

    queryset = industry.objects.all()

    queryset2 = industry.objects.filter(category__contains="Manufacturing")

    queryset3 = industry.objects.filter(category__contains="Automobile")

    queryset4 = industry.objects.filter(category__contains="Assembling")

    queryset5 = industry.objects.filter(category__contains="IT Companies")


    context = {
        "objects" : queryset,
        "objects2" : queryset2,
        "objects3":queryset3,
        "objects4":queryset4,
        "objects5":queryset5,

    }
    return render(request,'searchBarApp/Automobiles.html',context)

def Manufacturing(request,name=None):

    queryset = industry.objects.all()

    queryset2 = industry.objects.filter(category__contains="Manufacturing")

    queryset3 = industry.objects.filter(category__contains="Automobile")

    queryset4 = industry.objects.filter(category__contains="Assembling")

    queryset5 = industry.objects.filter(category__contains="IT Companies")


    context = {
        "objects" : queryset,
        "objects2" : queryset2,
        "objects3":queryset3,
        "objects4":queryset4,
        "objects5":queryset5,


    }
    return render(request,'searchBarApp/Manufacturing.html',context)

def IT_Companies(request,name=None):

    queryset = industry.objects.all()

    queryset2 = industry.objects.filter(category__contains="Manufacturing")

    queryset3 = industry.objects.filter(category__contains="Automobile")

    queryset4 = industry.objects.filter(category__contains="Assembling")

    queryset5 = industry.objects.filter(category__contains="IT Companies")


    context = {
        "objects" : queryset,
        "objects2" : queryset2,
        "objects3":queryset3,
        "objects4":queryset4,
        "objects5":queryset5,

    }
    return render(request,'searchBarApp/IT_Companies.html',context)

def base(request):

    queryset = industry.objects.all()

    queryset2 = industry.objects.filter(category__contains="Manufacturing")

    queryset3 = industry.objects.filter(category__contains="Automobile")

    queryset4 = industry.objects.filter(category__contains="Assembling")

    queryset5 = industry.objects.filter(category__contains="IT Companies")



    context = {
    "objects" : queryset,
    "objects2" : queryset2,
    "objects3":queryset3,
    "objects4":queryset4,
    "objects5":queryset5,

    }

    return render(request,'searchBarApp/base.html',context)

def contact(request):
    queryset = industry.objects.all()

    queryset2 = industry.objects.filter(category__contains="Manufacturing")

    queryset3 = industry.objects.filter(category__contains="Automobile")

    queryset4 = industry.objects.filter(category__contains="Assembling")

    queryset5 = industry.objects.filter(category__contains="IT Companies")


    context = {
        "objects" : queryset,
        "objects2" : queryset2,
        "objects3":queryset3,
        "objects4":queryset4,
        "objects5":queryset5,

    }
    return render(request,'searchBarApp/contact.html',context)

def blog(request):
    queryset = industry.objects.all()

    queryset2 = industry.objects.filter(category__contains="Manufacturing")

    queryset3 = industry.objects.filter(category__contains="Automobile")

    queryset4 = industry.objects.filter(category__contains="Assembling")

    queryset5 = industry.objects.filter(category__contains="IT Companies")


    context = {
        "objects" : queryset,
        "objects2" : queryset2,
        "objects3":queryset3,
        "objects4":queryset4,
        "objects5":queryset5,

    }
    return render(request,'searchBarApp/blog.html',context)

def faq(request):
    queryset = industry.objects.all()

    queryset2 = industry.objects.filter(category__contains="Manufacturing")

    queryset3 = industry.objects.filter(category__contains="Automobile")

    queryset4 = industry.objects.filter(category__contains="Assembling")

    queryset5 = industry.objects.filter(category__contains="IT Companies")


    context = {
        "objects" : queryset,
        "objects2" : queryset2,
        "objects3":queryset3,
        "objects4":queryset4,
        "objects5":queryset5,

    }
    return render(request,'searchBarApp/faq.html',context)

def about(request):
    queryset = industry.objects.all()

    queryset2 = industry.objects.filter(category__contains="Manufacturing")

    queryset3 = industry.objects.filter(category__contains="Automobile")

    queryset4 = industry.objects.filter(category__contains="Assembling")

    queryset5 = industry.objects.filter(category__contains="IT Companies")


    context = {
        "objects" : queryset,
        "objects2" : queryset2,
        "objects3":queryset3,
        "objects4":queryset4,
        "objects5":queryset5,

    }
    return render(request,'searchBarApp/about.html',context)

def services(request):
    queryset = industry.objects.all()

    queryset2 = industry.objects.filter(category__contains="Manufacturing")

    queryset3 = industry.objects.filter(category__contains="Automobile")

    queryset4 = industry.objects.filter(category__contains="Assembling")

    queryset5 = industry.objects.filter(category__contains="IT Companies")


    context = {
        "objects" : queryset,
        "objects2" : queryset2,
        "objects3":queryset3,
        "objects4":queryset4,
        "objects5":queryset5,

    }
    return render(request,'searchBarApp/services.html',context)

def read(request):
    queryset = industry.objects.all()

    queryset2 = industry.objects.filter(category__contains="Manufacturing")

    queryset3 = industry.objects.filter(category__contains="Automobile")

    queryset4 = industry.objects.filter(category__contains="Assembling")

    queryset5 = industry.objects.filter(category__contains="IT Companies")


    context = {
        "objects" : queryset,
        "objects2" : queryset2,
        "objects3":queryset3,
        "objects4":queryset4,
        "objects5":queryset5,

    }
    return render(request,'searchBarApp/read.html',context)

searchBar/searchBarApp/templates/searchBarApp/Assembling.html
<!DOCTYPE html>
{% extends 'searchBarApp/base.html'%}
{%block body_block%}
<br><br><br><br><br><br><br><br>
<br><br>

<div>
  <h1 style="text-align:center">
  	Assembling
  </h1>
</div>

<div>
  <h4 style="text-align:center">
  	Check out Assembling Industries
  </h4>
</div>

<br><br><br>
<div class="container">
<div class="row">
{% for obj in objects4 %}
<div class="col-sm-4">
<div class="card" style="width:300px">
    <img class="card-img-top" src="/media/{{obj.image}}" style="height:300px" alt="Card image" >
    <div class="card-body">
      <h4 class="card-title">{{obj.id_name}}</h4>
      <a href="#" class="btn btn-primary">See Profile</a>
    </div>
</div>
</div>
{% endfor %}
</div>
</div>
<br><br>
{%endblock%}

searchBar/searchBarApp/templates/searchBarApp/about.html
<!DOCTYPE html>
{% extends 'searchBarApp/base.html'%}

{%block body_block%}
<br><br><br><br><br><br><br>
<h1 style="text-align:center">About Visit+</h1>

<p>Visit+ is web service started by group of students to make things easier for practical knowledge seekers .</p>


<br><br><br><br>


{%endblock%}

searchBar/searchBarApp/templates/searchBarApp/blog.html
<!DOCTYPE html>
{% extends 'searchBarApp/base.html'%}

{%block body_block%}
<!-- <br><br><br><br><br><br><br>
<!-- <h1 style="text-align:center">Blog</h1> -->

<!-- <br>
<br><br><br>
<br><br><br>
<br><br><br>
<br><br><br>-->
<br><br><br><br>

<div class="stuff">
	<div class="container">
		<div class="row">

			<!-- FAQ -->
			<!-- <div class="col-lg-7">
				<div class="faq">
					<div class="faq_title">Faq & Stuff</div>
					<div class="faq_subtitle">read all about it</div>
					<div class="elements_accordions">
						<div class="accordions" >

							<div class="accordion_container" >
								<div class="accordion d-flex flex-row align-items-center active" ><div>What is  Visit <span>+</span></div></div>
								<div class="accordion_panel" >
									<div>
										<p>Visit+ is an web service founded by group of students .This makes your visit to any available company/industry easy .</p>
									</div>
								</div>
							</div>

							<div class="accordion_container">
								<div class="accordion d-flex flex-row align-items-center"><div>How to avail the service of visit+</div></div>
								<div class="accordion_panel">
									<div>
										<p>First of all,sign up for visit+ with email verified and enjoy the services of visit+</p>
									</div>
								</div>
							</div>

							<div class="accordion_container">
								<div class="accordion d-flex flex-row align-items-center"><div>Why is it important to have practical knowledge</div></div>
								<div class="accordion_panel">
									<div>
										<p>Very important skill to have in this competitive world</p>
									</div>
								</div>
							</div>

							<div class="accordion_container">
								<div class="accordion d-flex flex-row align-items-center"><div>How to avail the service of visit+</div></div>
								<div class="accordion_panel">
									<div>
										<p>First of all,sign up for visit+ with email verified and enjoy the services of visit+</p>
									</div>
								</div>
							</div>
							<div class="button home_button" style="background-color:#3385ff;"><a href="{% url 'searchBarApp:faq' %}"><span>read more</span><span>read whole</span></a></div>

						</div>
					</div>
				</div>
			</div>

			<!-- Latest News -->
			<div class="col-lg-5">
				<div class="news" >
					<div class="news_title" style="padding-left:100px">Blog</div>
					<div class="news_subtitle" style="padding-left:100px">Read all about it</div>
					<div class="news_container">

						<!-- Latest News Post -->
						<div class="latest d-flex flex-row align-items-start justify-content-start">
							<div><div class="latest_image"><img src="images/latest_1.jpg" alt=""></div></div>
							<div class="latest_content">
								<div class="latest_title"><a href="news.html">A simple blog post</a></div>
								<div class="latest_info">
									<ul class="d-flex flex-row align-items-start justify-content-start">
										<li><a href="#">by Sumanth</a></li>
										<li><a href="#">November 1, 2018</a></li>
									</ul>
								</div>
								<div class="latest_comments"><a href="#" style="color:#3385ff;">7 Comments</a></div>
							</div>
						</div>

						<!-- Latest News Post -->
						<div class="latest d-flex flex-row align-items-start justify-content-start">
							<div><div class="latest_image"><img src="images/latest_2.jpg" alt=""></div></div>
							<div class="latest_content">
								<div class="latest_title"><a href="news.html">Great Experience to visit kobelcoo</a></div>
								<div class="latest_info">
									<ul class="d-flex flex-row align-items-start justify-content-start">
										<li><a href="#">by Hemanth</a></li>
										<li><a href="#">November 1, 2018</a></li>
									</ul>
								</div>
								<div class="latest_comments"><a href="#" style="color:#3385ff;">5 Comments</a></div>
							</div>
						</div>

						<!-- Latest News Post -->
						<div class="latest d-flex flex-row align-items-start justify-content-start">
							<div><div class="latest_image"><img src="images/latest_3.jpg" alt=""></div></div>
							<div class="latest_content">
								<div class="latest_title"><a href="news.html">How to make a industrial tour successfull??</a></div>
								<div class="latest_info">
									<ul class="d-flex flex-row align-items-start justify-content-start">
										<li><a href="#">by Pranay</a></li>
										<li><a href="#">November 1, 2018</a></li>
									</ul>
								</div>
								<div class="latest_comments" ><a href="#" style="color:#3385ff;">2 Comments</a></div>
							</div>
						</div>

            <div class="latest d-flex flex-row align-items-start justify-content-start">
							<div><div class="latest_image"><img src="images/latest_3.jpg" alt=""></div></div>
							<div class="latest_content">
								<div class="latest_title"><a href="news.html">How to  learn things from industrial tour ??</a></div>
								<div class="latest_info">
									<ul class="d-flex flex-row align-items-start justify-content-start">
										<li><a href="#">by Lushanak</a></li>
										<li><a href="#">January 21, 2018</a></li>
									</ul>
								</div>
								<div class="latest_comments" ><a href="#" style="color:#3385ff;">4 Comments</a></div>
							</div>
						</div>

					</div>
				</div>
			</div>

		</div>
</div>
</div>


{%endblock%}

searchBar/searchBarApp/templates/searchBarApp/contact.html
<!DOCTYPE html>
{% extends 'searchBarApp/base.html'%}

{%block body_block%}
<br><br><br><br><br><br><br>
<h1 style="text-align:center">Contact us</h1>

<br><br><br><br>


{%endblock%}

searchBar/searchBarApp/templates/searchBarApp/index.html
<!DOCTYPE html>
{% extends 'searchBarApp/base.html'%}

{% load staticfiles %}
{% block body_block %}

<div class="home"><!--{% static "images/contact.jpg" %}-->
		<div class="background_image" style="background-image:url({%static  "images/background_main.jpg " %} )"></div>

<div class="home_container">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="home_content" style="padding-top:200px">
						<div class="home_title" >Visitings made easy</div>
						<div class="home_text" style="color:yellow">Explore the joy of visiting companies that you love </div>
						<div class="button home_button" style="background-color:#3385ff;"><a href="{% url 'searchBarApp:read' %}"><span>read more</span><span>read whole</span></a></div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<br><br><br>


<!-- Departments -->

<div class="departments">
 <div class="container">
	 <div class="row">
		 <div class="col text-center">
			 <div class="section_title">Our Departments</div>
			 <div class="section_subtitle">to choose from</div>
		 </div>
	 </div>
	 <div class="row dept_row">
		 <div class="col">
			 <div class="dept_slider_container_outer">
				 <div class="dept_slider_container">

					 <!-- Slider -->
					 <div class="owl-carousel owl-theme dept_slider">

						 <!-- Slide -->
						 <div class="owl-item dept_item" >
							 <div class="dept_image"><img src="{%static  "images/Manufacturing.jpg " %}" height="170" alt=""></div>
							 <div class="dept_content"  >
								 <div class="dept_title">Manufacturing</div>
								 <div class="dept_link" ><a href="{% url 'searchBarApp:Manufacturing' %}">Read More</a></div>
							 </div>
						 </div>

						 <!-- Slide -->
						 <div class="owl-item dept_item">
							 <div class="dept_image"><img src="{%static  "images/assembling.jpg " %}" alt=""></div>
							 <div class="dept_content">
								 <div class="dept_title">Assembling</div>
								 <div class="dept_link"><a href="{% url 'searchBarApp:Assembling' %}">Read More</a></div>
							 </div>
						 </div>

						 <!-- Slide -->
						 <div class="owl-item dept_item">
							 <div class="dept_image"><img src="{%static  "images/IT_Companies.jpg " %}" alt=""></div>
							 <div class="dept_content">
								 <div class="dept_title">IT Companies</div>
								 <div class="dept_link"><a href="{% url 'searchBarApp:IT_Companies' %}">Read More</a></div>
							 </div>
						 </div>

						 <!-- Slide -->
						 <div class="owl-item dept_item">
							 <div class="dept_image"><img src="{%static  "images/Automobiles.jpg " %}" alt=""></div>
							 <div class="dept_content">
								 <div class="dept_title">AutoMobiles</div>
								 <div class="dept_link"><a href="{% url 'searchBarApp:Automobiles' %}" >Read More</a></div>
							 </div>
						 </div>

					 </div>

				 </div>

				 <!-- Dept Slider Nav -->
				 <div class="dept_slider_nav" style="background-color:#3385ff;"><i class="fa fa-chevron-right" aria-hidden="true"></i></div>

			 </div>

		 </div>
	 </div>
 </div>
</div>

<!-- Services -->

<div class="services">
	<div class="container">
		<div class="row">
			<div class="col text-center">
				<div class="section_title">Our Services</div>
				<div class="section_subtitle">to choose from</div>
			</div>
		</div>
		<div class="row icon_boxes_row">

			<!-- Icon Box -->
			<div class="col-xl-4 col-lg-6">
				<div class="icon_box">
					<div class="icon_box_title_container d-flex flex-row align-items-center justify-content-start">
						 <div class="icon_box_icon"><img src="https://img.freepik.com/free-icon/bus-side-view_318-47219.jpg?size=338c&ext=jpg" alt=""></div>
						<div class="icon_box_title">Travel</div>
					</div>
					<div class="icon_box_text">We can provide bus services from railway station to industry .To avail this,Just pay money and make your tour a memorable one.</div>
				</div>
			</div>

			<!-- Icon Box -->
			<div class="col-xl-4 col-lg-6">
				<div class="icon_box">
					<div class="icon_box_title_container d-flex flex-row align-items-center justify-content-start">
						<div class="icon_box_icon"><img src="https://img.freepik.com/free-icon/bus-side-view_318-47219.jpg?size=338c&ext=jpg" alt=""></div>
						<div class="icon_box_title">Travel</div>
					</div>
					<div class="icon_box_text">We can provide bus services from railway station to industry .To avail this,Just pay money and make your tour a memorable one.</div>
				</div>
			</div>

			<!-- Icon Box -->
			<div class="col-xl-4 col-lg-6">
				<div class="icon_box">
					<div class="icon_box_title_container d-flex flex-row align-items-center justify-content-start">
						<div class="icon_box_icon"><img src="https://img.freepik.com/free-icon/bus-side-view_318-47219.jpg?size=338c&ext=jpg" alt=""></div>
						<div class="icon_box_title">Travel</div>
					</div>
					<div class="icon_box_text">We can provide bus services from railway station to industry .To avail this,Just pay money and make your tour a memorable one.</div>
				</div>
			</div>

			<!-- Icon Box -->
			<div class="col-xl-4 col-lg-6">
				<div class="icon_box">
					<div class="icon_box_title_container d-flex flex-row align-items-center justify-content-start">
						<div class="icon_box_icon"><img src="https://img.freepik.com/free-icon/bus-side-view_318-47219.jpg?size=338c&ext=jpg" alt=""></div>
						<div class="icon_box_title">Travel</div>
					</div>
					<div class="icon_box_text">We can provide bus services from railway station to industry .To avail this,Just pay money and make your tour a memorable one.</div>
				</div>
			</div>

			<!-- Icon Box -->
			<div class="col-xl-4 col-lg-6">
				<div class="icon_box">
					<div class="icon_box_title_container d-flex flex-row align-items-center justify-content-start">
						<div class="icon_box_icon"><img src="https://img.freepik.com/free-icon/bus-side-view_318-47219.jpg?size=338c&ext=jpg" alt=""></div>
						<div class="icon_box_title">Travel</div>
					</div>
					<div class="icon_box_text">We can provide bus services from railway station to industry .To avail this,Just pay money and make your tour a memorable one.</div>
				</div>
			</div>

			<!-- Icon Box -->
			<div class="col-xl-4 col-lg-6">
				<div class="icon_box">
					<div class="icon_box_title_container d-flex flex-row align-items-center justify-content-start">
						<div class="icon_box_icon"><img src="https://img.freepik.com/free-icon/bus-side-view_318-47219.jpg?size=338c&ext=jpg" alt=""></div>
						<div class="icon_box_title">Travel</div>
					</div>
					<div class="icon_box_text">We can provide bus services from railway station to industry .To avail this,Just pay money and make your tour a memorable one.</div>
				</div>
			</div>

		</div>
		<div class="row">
			<div class="col">
				<div class="button services_button ml-auto mr-auto" style="background-color:#3385ff;"><a href="#"><span>read more</span><span>read more</span></a></div>
			</div>
		</div>
	</div>
</div>

<!-- FAQ & News -->

<div class="stuff">
	<div class="container">
		<div class="row">

			<!-- FAQ -->
			<div class="col-lg-7">
				<div class="faq">
					<div class="faq_title">Faq & Stuff</div>
					<div class="faq_subtitle">read all about it</div>
					<div class="elements_accordions">
						<div class="accordions" >

							<div class="accordion_container" >
								<div class="accordion d-flex flex-row align-items-center active" ><div>What is  Visit <span>+</span></div></div>
								<div class="accordion_panel" >
									<div>
										<p>Visit+ is an web service founded by group of students .This makes your visit to any available company/industry easy .</p>
									</div>
								</div>
							</div>

							<div class="accordion_container">
								<div class="accordion d-flex flex-row align-items-center"><div>How to avail the service of visit+</div></div>
								<div class="accordion_panel">
									<div>
										<p>First of all,sign up for visit+ with email verified and enjoy the services of visit+</p>
									</div>
								</div>
							</div>

							<div class="accordion_container">
								<div class="accordion d-flex flex-row align-items-center"><div>Why is it important to have practical knowledge</div></div>
								<div class="accordion_panel">
									<div>
										<p>Very important skill to have in this competitive world</p>
									</div>
								</div>
							</div>

							<div class="accordion_container">
								<div class="accordion d-flex flex-row align-items-center"><div>How to avail the service of visit+</div></div>
								<div class="accordion_panel">
									<div>
										<p>First of all,sign up for visit+ with email verified and enjoy the services of visit+</p>
									</div>
								</div>
							</div>
							<div class="button home_button" style="background-color:#3385ff;"><a href="{% url 'searchBarApp:faq' %}"><span>read more</span><span>read whole</span></a></div>

						</div>
					</div>
				</div>
			</div>

			<!-- Latest News -->
			<div class="col-lg-5">
				<div class="news" >
					<div class="news_title" style="padding-left:100px">Blog</div>
					<div class="news_subtitle" style="padding-left:100px">Read all about it</div>
					<div class="news_container">

						<!-- Latest News Post -->
						<div class="latest d-flex flex-row align-items-start justify-content-start">
							<div><div class="latest_image"><img src="images/latest_1.jpg" alt=""></div></div>
							<div class="latest_content">
								<div class="latest_title"><a href="news.html">A simple blog post</a></div>
								<div class="latest_info">
									<ul class="d-flex flex-row align-items-start justify-content-start">
										<li><a href="#">by Sumanth</a></li>
										<li><a href="#">November 1, 2018</a></li>
									</ul>
								</div>
								<div class="latest_comments"><a href="#" style="color:#3385ff;">7 Comments</a></div>
							</div>
						</div>

						<!-- Latest News Post -->
						<div class="latest d-flex flex-row align-items-start justify-content-start">
							<div><div class="latest_image"><img src="images/latest_2.jpg" alt=""></div></div>
							<div class="latest_content">
								<div class="latest_title"><a href="news.html">Great Experience to visit kobelcoo</a></div>
								<div class="latest_info">
									<ul class="d-flex flex-row align-items-start justify-content-start">
										<li><a href="#">by Hemanth</a></li>
										<li><a href="#">November 1, 2018</a></li>
									</ul>
								</div>
								<div class="latest_comments"><a href="#" style="color:#3385ff;">5 Comments</a></div>
							</div>
						</div>

						<!-- Latest News Post -->
						<div class="latest d-flex flex-row align-items-start justify-content-start">
							<div><div class="latest_image"><img src="images/latest_3.jpg" alt=""></div></div>
							<div class="latest_content">
								<div class="latest_title"><a href="news.html">How to make a industrial tour successfull??</a></div>
								<div class="latest_info">
									<ul class="d-flex flex-row align-items-start justify-content-start">
										<li><a href="#">by Pranay</a></li>
										<li><a href="#">November 1, 2018</a></li>
									</ul>
								</div>
								<div class="latest_comments" ><a href="#" style="color:#3385ff;">2 Comments</a></div>
							</div>
						</div>

					</div>
				</div>
			</div>

		</div>
</div>
</div>



{% endblock %}